version: "3.8"
services:
  tools:
    build:
      context: ./docker/php
      dockerfile: cli/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
        XDEBUG_VERSION: ${XDEBUG_VERSION}
        COMPOSER_VERSION: ${COMPOSER_VERSION}
    image: spip/tools:8.1
    networks:
    - dev.spip.local
    hostname: tools
    container_name: tools
    volumes:
    - ./apps:/build
    env_file:
      .env
    environment:
    - XDEBUG_CONFIG="idekey=my-ide-key"

  sql:
    image: mariadb:10.6
    networks:
    - dev.spip.local
    hostname: sql
    container_name: sql
    volumes:
    - ./data/spip:/var/lib/mysql
    - ./docker/sql/mariadb/10.3:/docker-entrypoint-initdb.d
    environment:
    - MYSQL_ROOT_PASSWORD=spip
    - MYSQL_DATABASE=spip

  dev.spip.local:
    build:
      context: ./docker/php
      dockerfile: apache/8.1/Dockerfile
    image: spip/apache:8.3.4
    networks:
    - dev.spip.local
    ports:
    - "8000:80"
    hostname: dev.spip.local
    container_name: dev.spip.local
    volumes:
    - ./apps/spip:/var/www/html
    environment:
    - MYSQL_HOST=sql
    - MYSQL_DATABASE=spip
    - MYSQL_USER=root
    - MYSQL_PASSWORD=spip
    - XDEBUG_CONFIG="idekey=my-ide-key"
    depends_on:
    - sql

networks:
  dev.spip.local:
